
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

process.env.SEROS_PROVIDER = 'fake';          // deterministic, offline
process.env.SEROS_SIGNING_SECRET = 'test-secret';

const dir = mkdtempSync(join(tmpdir(), 'seros-audit-test-'));
process.env.SEROS_DB = join(dir, 'test.db');

import { migrateDb, openDb } from '../src/db/client';
import { WorkspaceScope } from '../src/db/scope';
import { auditEvents, workspaces } from '../src/db/schema';
import { deleteWorkspace, ensureRetentionSchema } from '../src/retention';
import { and, eq, sql } from 'drizzle-orm';

migrateDb();
const db = openDb();
ensureRetentionSchema(db);

/** M11 / brief §1.11: the fields an AuditEvent must carry ... */
const MANDATED_FIELDS = [
  'workspace_id', 'id', 'actor_type', 'actor_id', 'event', 'object_type', 'object_id',
  'outcome', 'request_id', 'detail', 'at',
] as const;
/** ... and the ones that may never be null or empty on any row. */
const REQUIRED_FIELDS = ['workspace_id', 'id', 'actor_type', 'event', 'outcome', 'request_id', 'at'] as const;

/**
 * Run a write that must be refused and return its whole error chain as text.
 * drizzle wraps a raw statement's failure, so the trigger's own message is in
 * `cause`; a builder failure surfaces directly. Both are checked the same way.
 */
function refusal(fn: () => unknown): string {
  try {
    fn();
  } catch (e) {
    const parts: string[] = [];
    let err: unknown = e;
    while (err instanceof Error) { parts.push(err.message); err = err.cause; }
    return parts.join(' | ');
  }
  return assert.fail('the write was NOT refused');
}

function rows(workspaceId: string) {
  return db.select().from(auditEvents).where(eq(auditEvents.workspaceId, workspaceId)).all();
}
/** The physical columns of the audit table, straight from SQLite. */
function columns(): string[] {
  return (db.all(sql`PRAGMA table_info(audit_log)`) as any[]).map((c) => c.name as string);
}

test('audit: the table carries every field the brief mandates', () => {
  const present = columns();
  for (const f of MANDATED_FIELDS) assert.ok(present.includes(f), `audit_log is missing ${f}`);
});

test('audit: a row written by the existing four-argument writer is fully populated', () => {
  const s = WorkspaceScope.ensure(db, 'A-fields');
  s.audit('connection.created', 'ok', { connection_id: 'c-1', channel_count: 2 });

  const row = rows('A-fields')[0];
  assert.ok(row, 'the writer wrote nothing');
  const raw = db.all(sql`SELECT * FROM audit_log WHERE workspace_id = ${'A-fields'}`)[0] as Record<string, unknown>;
  for (const f of REQUIRED_FIELDS) {
    assert.notEqual(raw[f], null, `${f} is null`);
    assert.notEqual(raw[f], '', `${f} is empty`);
  }
  assert.equal(row.workspaceId, 'A-fields');
  assert.equal(row.event, 'connection.created');
  assert.equal(row.outcome, 'ok');
  // an un-attributed write is the SYSTEM actor, not a missing one
  assert.equal(row.actorType, 'system');
  // invariant 12: a request id on every entry, generated by the database when the
  // caller has none, so no row can exist without a correlation handle
  assert.equal(typeof row.requestId, 'string');
  assert.ok(row.requestId.length >= 8);
  assert.ok(row.at > 0);
});

test('audit: an actor, a subject and a request id are recorded when the caller supplies them', () => {
  const s = WorkspaceScope.ensure(db, 'A-actor');
  db.insert(auditEvents).values({
    workspaceId: s.workspaceId, event: 'draft.confirmed', outcome: 'ok',
    actorType: 'member', actorId: 'm-ana',
    objectType: 'draft', objectId: 'd-42',
    requestId: 'req-abc-123',
    detail: JSON.stringify({ confirmation_id: 'k-1' }), at: Date.now(),
  }).run();

  const row = rows('A-actor')[0]!;
  assert.equal(row.actorType, 'member');
  assert.equal(row.actorId, 'm-ana');
  assert.equal(row.objectType, 'draft');
  assert.equal(row.objectId, 'd-42');
  assert.equal(row.requestId, 'req-abc-123');
});

test('audit: the three actor kinds are distinguishable and nothing else is accepted', () => {
  const s = WorkspaceScope.ensure(db, 'A-kinds');
  for (const [kind, id] of [['member', 'm-1'], ['system', null], ['operator', 'op-7']] as const) {
    db.insert(auditEvents).values({
      workspaceId: s.workspaceId, event: 'operator.accessed', outcome: 'ok',
      actorType: kind, actorId: id, at: Date.now(),
    }).run();
  }
  assert.deepEqual(rows('A-kinds').map((r) => r.actorType).sort(), ['member', 'operator', 'system']);

  assert.match(refusal(() => db.insert(auditEvents).values({
    workspaceId: s.workspaceId, event: 'x', outcome: 'ok',
    actorType: 'robot' as any, at: Date.now(),
  }).run()), /CHECK/);

  // a member actor is a real person (invariant 4): it must be identified
  assert.match(refusal(() => db.insert(auditEvents).values({
    workspaceId: s.workspaceId, event: 'draft.confirmed', outcome: 'ok',
    actorType: 'member', actorId: null, at: Date.now(),
  }).run()), /CHECK/);
});

test('audit: an UPDATE of an audit row is refused by the database', () => {
  const s = WorkspaceScope.ensure(db, 'A-update');
  s.audit('draft.confirmed', 'ok', { draft_id: 'd-1' });
  const before = rows('A-update')[0]!;

  // through the ORM ...
  assert.match(refusal(() => db.update(auditEvents).set({ outcome: 'failed' })
    .where(eq(auditEvents.workspaceId, 'A-update')).run()), /append-only/i);
  // ... and underneath it, in raw SQL, which is the point of the finding
  assert.match(refusal(() => db.run(sql`UPDATE audit_log SET event = 'rewritten' WHERE id = ${before.id}`)), /append-only/i);
  assert.match(refusal(() => db.run(sql`UPDATE audit_log SET detail = NULL`)), /append-only/i);

  assert.deepEqual(rows('A-update')[0], before, 'the row moved despite the refusal');
});

test('audit: a DELETE of an audit row is refused by the database', () => {
  const s = WorkspaceScope.ensure(db, 'A-delete');
  s.audit('task.created', 'ok', { task_id: 't-1' });
  s.audit('task.created', 'ok', { task_id: 't-2' });

  assert.match(refusal(() => db.delete(auditEvents).where(eq(auditEvents.workspaceId, 'A-delete')).run()), /append-only/i);
  assert.match(refusal(() => db.run(sql`DELETE FROM audit_log WHERE workspace_id = ${'A-delete'}`)), /append-only/i);
  assert.match(refusal(() => db.run(sql`DELETE FROM audit_log`)), /append-only/i);

  assert.equal(rows('A-delete').length, 2);
});

test('audit: the append-only ban holds inside a transaction', () => {
  const s = WorkspaceScope.ensure(db, 'A-tx');
  s.audit('session.started', 'ok', { member_id: 'm-1' });

  assert.match(refusal(() => db.transaction((tx) => {
    tx.run(sql`DELETE FROM audit_log WHERE workspace_id = ${'A-tx'}`);
  })), /append-only/i);
  assert.equal(rows('A-tx').length, 1);
});

test('audit: ids are monotonic, across workspaces and after a refused write', () => {
  const a = WorkspaceScope.ensure(db, 'A-mono-a');
  const b = WorkspaceScope.ensure(db, 'A-mono-b');
  const seen: number[] = [];
  for (let i = 0; i < 5; i++) {
    a.audit('message.ingested', 'ok', { message_id: `m-${i}` });
    seen.push(rows('A-mono-a').at(-1)!.id);
    b.audit('message.ingested', 'ok', { message_id: `n-${i}` });
    seen.push(rows('A-mono-b').at(-1)!.id);
  }
  for (let i = 1; i < seen.length; i++) {
    assert.ok(seen[i]! > seen[i - 1]!, `id ${seen[i]} did not follow ${seen[i - 1]}`);
  }

  // a refused delete must not free an id for reuse either
  assert.match(refusal(() => db.run(sql`DELETE FROM audit_log WHERE workspace_id = ${'A-mono-a'}`)), /append-only/i);
  a.audit('message.ingested', 'ok', { message_id: 'm-last' });
  assert.ok(rows('A-mono-a').at(-1)!.id > seen.at(-1)!);
});

test('audit: the database refuses a detail that carries a content field', () => {
  const s = WorkspaceScope.ensure(db, 'A-content');
  for (const key of ['body', 'text', 'title', 'content', 'message', 'permalink', 'summary']) {
    assert.match(refusal(() => s.audit('draft.created', 'ok', { [key]: 'the secret quarterly numbers are 42' })),
                 /CHECK/, `a detail carrying "${key}" was accepted`);
  }
  // ... while the field NAMES, counts and ids that belong there are accepted
  s.audit('draft.edited', 'ok', { draft_id: 'd-1', edited_fields: 'title,outcome', edited_count: 2 });
  s.audit('message.ingested', 'ok', { message_id: 'm-1' });
  assert.equal(rows('A-content').length, 2);
});

test('audit: a full ingest-to-task flow puts no content value in the log', () => {
  const SECRET = 'the acquisition price is 4.2 million';
  const s = WorkspaceScope.ensure(db, 'A-flow');
  s.addMember('m-ana', 'Ana', 'confirmer');
  const { row } = s.ingestMessage({ channelId: 'C1', ts: '900.1', authorId: 'u-ana', body: SECRET });
  const draftId = s.createDraft({
    sourceMessageId: row.id, title: SECRET, outcome: SECRET, kind: 'commitment',
    confidence: 90, suggestedOwner: 'u-ana', suggestedDueDate: null, provider: 'fake',
  });
  const r = s.confirm(draftId, 'confirmed_with_edits', 'm-ana', { title: `${SECRET} (edited)` });
  assert.equal(r.ok, true);

  const all = rows('A-flow');
  assert.ok(all.length >= 4, 'the flow recorded almost nothing');
  for (const e of all) {
    const serialised = JSON.stringify(e);
    assert.ok(!serialised.includes(SECRET), `audit row ${e.id} carried content (${e.event})`);
    assert.ok(!serialised.includes('acquisition'), `audit row ${e.id} carried a content word (${e.event})`);
    assert.ok(e.requestId.length > 0, `audit row ${e.id} has no request id`);
    assert.ok(['member', 'system', 'operator'].includes(e.actorType), `audit row ${e.id} has no actor kind`);
    assert.ok(e.at > 0);
  }
  // what the human changed is recorded as FIELD NAMES, never as the values
  const edited = all.find((e) => e.event === 'draft.edited')!;
  assert.ok(edited.detail!.includes('edited_fields'));
  assert.ok(!edited.detail!.includes(SECRET));
});

test('audit: the rows survive workspace deletion, and cannot be deleted with it', () => {
  const s = WorkspaceScope.ensure(db, 'A-wsdel');
  s.addMember('m-ana', 'Ana', 'confirmer');
  const { row } = s.ingestMessage({ channelId: 'C1', ts: '901.1', authorId: 'u-ana', body: 'something said' });
  s.createDraft({
    sourceMessageId: row.id, title: 'ship the thing', outcome: 'shipped', kind: 'commitment',
    confidence: 80, suggestedOwner: 'u-ana', suggestedDueDate: null, provider: 'fake',
  });
  const before = rows('A-wsdel');
  assert.ok(before.length >= 2);

  const result = deleteWorkspace(db, 'A-wsdel');
  assert.equal(result.status, 'deleted');

  const after = rows('A-wsdel');
  assert.ok(after.length > before.length, 'deletion wrote no completion record');
  for (const e of before) {
    assert.deepEqual(after.find((x) => x.id === e.id), e, `audit row ${e.id} did not survive the deletion intact`);
  }
  assert.ok(after.some((e) => e.event === 'workspace.deleted'));
  // the workspace_id stays on the row as a reference (§1.1), against a tombstone
  assert.ok(after.every((e) => e.workspaceId === 'A-wsdel'));
  assert.equal(db.select().from(workspaces).where(eq(workspaces.id, 'A-wsdel')).get()!.status, 'deleted');

  // and a second pass at the log, now that the workspace is gone, is still refused
  assert.match(refusal(() => db.run(sql`DELETE FROM audit_log WHERE workspace_id = ${'A-wsdel'}`)), /append-only/i);
  assert.equal(rows('A-wsdel').length, after.length);
});

test('audit: rows stay readable and workspace-scoped after all of this', () => {
  const s = WorkspaceScope.ensure(db, 'A-read');
  s.audit('session.started', 'ok', { member_id: 'm-1' });
  s.audit('draft.confirm_denied', 'denied', { member_id: 'm-1', draft_id: 'd-9' });
  const seen = db.select().from(auditEvents)
    .where(and(eq(auditEvents.workspaceId, 'A-read'), eq(auditEvents.outcome, 'denied'))).all();
  assert.equal(seen.length, 1);
  assert.equal(seen[0]!.event, 'draft.confirm_denied');
});

test.after(() => rmSync(dir, { recursive: true, force: true }));
