-- migrations/pg/0001_schema.sql
-- Postgres mirror of migrations/0001_initial_schema.sql.
--
-- Same tables, same columns, same CHECK constraints, same composite PRIMARY KEYs
-- and the same FOREIGN KEYs - the invariants are enforced by the database on
-- purpose (ADR 0003), so nothing is relaxed here.
--
-- TYPE MAPPING (the only deliberate differences from the SQLite file):
--   * every column that carries epoch MILLISECONDS (created_at, received_at,
--     content_purged_at, run_at, at) is BIGINT: SQLite INTEGER is 64-bit, PG
--     INTEGER is 32-bit and would overflow at 2038-in-seconds / 1970-in-millis.
--     src/db/driver.ts registers an int8 -> Number parser so these come back as
--     JavaScript numbers, not strings, which is what every caller expects.
--   * plain counters (confidence, attempts, budgets, retention days) stay INTEGER.
--   * INTEGER PRIMARY KEY AUTOINCREMENT becomes BIGINT GENERATED BY DEFAULT AS
--     IDENTITY: monotonic, never reused, and still accepts an explicit id so the
--     0005 backfill can preserve history.
--   * integer-valued flags (billable_action) stay INTEGER rather than BOOLEAN,
--     because src/db/schema.ts declares them with drizzle's integer() and the
--     application reads them as 0/1. Changing the storage type here would change
--     the value the ORM hands back on Postgres only.
--
-- Idempotent: re-executed on every boot, exactly like the SQLite set.

CREATE TABLE IF NOT EXISTS workspaces (
  id                      TEXT PRIMARY KEY,
  name                    TEXT NOT NULL,
  status                  TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','suspended','deleting','deleted')),
  retention_content_days  INTEGER NOT NULL DEFAULT 30,
  daily_budget_cents      INTEGER NOT NULL DEFAULT 0,
  monthly_budget_cents    INTEGER NOT NULL DEFAULT 0,
  created_at              BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS members (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id),
  id           TEXT NOT NULL,
  name         TEXT NOT NULL,
  role         TEXT NOT NULL CHECK(role IN ('owner','admin','confirmer','viewer')),
  status       TEXT NOT NULL CHECK(status IN ('invited','active','suspended','removed')),
  PRIMARY KEY (workspace_id, id)
);

CREATE TABLE IF NOT EXISTS source_messages (
  workspace_id      TEXT NOT NULL REFERENCES workspaces(id),
  channel_id        TEXT NOT NULL,
  ts                TEXT NOT NULL,
  id                TEXT NOT NULL,
  author_id         TEXT NOT NULL,
  body              TEXT,            -- NULL once purged; identifiers survive
  body_hash         TEXT NOT NULL,
  content_purged_at BIGINT,
  received_at       BIGINT NOT NULL,
  PRIMARY KEY (workspace_id, channel_id, ts),
  UNIQUE (workspace_id, id)          -- the target of the drafts foreign key below
);

CREATE TABLE IF NOT EXISTS drafts (
  workspace_id       TEXT NOT NULL REFERENCES workspaces(id),
  id                 TEXT NOT NULL,
  source_message_id  TEXT NOT NULL,
  title              TEXT NOT NULL DEFAULT '',
  outcome            TEXT NOT NULL DEFAULT '',
  provider           TEXT,
  kind               TEXT NOT NULL CHECK(kind IN ('commitment','request','decision')),
  confidence         INTEGER NOT NULL,
  suppressed_reason  TEXT,
  suggested_due_date TEXT,
  suggested_owner    TEXT,
  state              TEXT NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','confirmed','rejected','expired','superseded')),
  created_at         BIGINT NOT NULL,
  PRIMARY KEY (workspace_id, id),
  FOREIGN KEY (workspace_id, source_message_id) REFERENCES source_messages(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS confirmations (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id),
  draft_id     TEXT NOT NULL,
  id           TEXT NOT NULL,
  decision     TEXT NOT NULL CHECK(decision IN ('confirmed','confirmed_with_edits','rejected')),
  surface      TEXT NOT NULL CHECK(surface IN ('web','slack_action')),
  member_id    TEXT NOT NULL,
  created_at   BIGINT NOT NULL,
  PRIMARY KEY (workspace_id, id),
  UNIQUE (workspace_id, draft_id),   -- one confirmation per draft: the race the app relies on
  FOREIGN KEY (workspace_id, draft_id)  REFERENCES drafts(workspace_id, id),
  FOREIGN KEY (workspace_id, member_id) REFERENCES members(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS tasks (
  workspace_id       TEXT NOT NULL REFERENCES workspaces(id),
  id                 TEXT NOT NULL,
  confirmation_id    TEXT NOT NULL,
  write_state        TEXT NOT NULL DEFAULT 'queued'  CHECK(write_state IN ('queued','created','failed','needs_review')),
  thread_reply_state TEXT NOT NULL DEFAULT 'pending' CHECK(thread_reply_state IN ('pending','posted','skipped','failed')),
  idempotency_key    TEXT NOT NULL,
  created_at         BIGINT NOT NULL,
  PRIMARY KEY (workspace_id, id),
  UNIQUE (workspace_id, confirmation_id),   -- 1:1 with its confirmation (ADR 0002)
  FOREIGN KEY (workspace_id, confirmation_id) REFERENCES confirmations(workspace_id, id)
);

-- Dead since 0005 (audit_log replaced it); created here only so an existing
-- database can be read once by the 0005 backfill, exactly as in the SQLite set.
CREATE TABLE IF NOT EXISTS audit_events (
  workspace_id TEXT   NOT NULL REFERENCES workspaces(id),
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event        TEXT   NOT NULL,
  outcome      TEXT   NOT NULL CHECK(outcome IN ('ok','denied','failed')),
  detail       TEXT,
  at           BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS jobs (
  workspace_id TEXT   NOT NULL REFERENCES workspaces(id),
  id           TEXT   NOT NULL,
  queue        TEXT   NOT NULL,
  status       TEXT   NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','done','failed','dead_letter')),
  payload      TEXT   NOT NULL,
  run_at       BIGINT NOT NULL,
  attempts     INTEGER NOT NULL DEFAULT 0,
  created_at   BIGINT NOT NULL,
  PRIMARY KEY (workspace_id, id)
);
