-- migrations/pg/0002_meter_cost.sql
-- Postgres mirror of migrations/0002_meter_cost.sql.
-- `action_meter` is owned by THIS file, exactly as in the SQLite set: the table is
-- created once in its full shape, so re-running the file on every boot is a no-op.
-- Contains no customer content by construction: ids, counts, prices, outcomes.

CREATE TABLE IF NOT EXISTS action_meter (
  workspace_id           TEXT    NOT NULL REFERENCES workspaces(id),
  id                     BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purpose                TEXT    NOT NULL CHECK(purpose IN ('detect','draft','route','replay','other')),
  outcome                TEXT    NOT NULL CHECK(outcome IN ('ok','timeout','invalid_output','provider_error','budget_blocked')),
  at                     BIGINT  NOT NULL,
  tier                   TEXT            CHECK(tier IS NULL OR tier IN ('cheap','standard','careful')),
  provider               TEXT,
  model                  TEXT,
  prompt_version         TEXT,
  input_tokens           INTEGER NOT NULL DEFAULT 0,
  output_tokens          INTEGER NOT NULL DEFAULT 0,
  cached_input_tokens    INTEGER NOT NULL DEFAULT 0,
  estimated_cost_micros  BIGINT  NOT NULL DEFAULT 0,   -- priced at call time, versioned table
  price_table_version    TEXT,
  latency_ms             INTEGER,
  ref_type               TEXT,                          -- what the call was for ...
  ref_id                 TEXT,                          -- ... so cost attaches to a draft
  billable_action        INTEGER NOT NULL DEFAULT 1     -- 0/1, not BOOLEAN: schema.ts reads it as a number
);

-- Budget reads are "spend for this workspace since <timestamp>", on every call.
CREATE INDEX IF NOT EXISTS action_meter_ws_at ON action_meter (workspace_id, at);
CREATE INDEX IF NOT EXISTS action_meter_at    ON action_meter (at);
