-- migrations/pg/0005_audit_append_only.sql
-- Postgres mirror of migrations/0005_audit_append_only.sql.
--
-- Same table, same columns, same CHECKs, same indexes, same append-only ban and
-- the same one-time backfill out of the dead `audit_events` table. The SQLite
-- file enforces append-only with two BEFORE triggers that RAISE(ABORT); Postgres
-- has no RAISE in plain SQL triggers, so the ban is a plpgsql trigger function
-- that RAISE EXCEPTIONs, wired to BEFORE UPDATE and BEFORE DELETE FOR EACH ROW.
-- The message still contains "append-only", which is what the audit tests match.
--
-- Idempotent, like every other file here: CREATE TABLE / INDEX IF NOT EXISTS,
-- CREATE OR REPLACE FUNCTION, and DROP TRIGGER IF EXISTS before CREATE TRIGGER
-- (Postgres has no CREATE TRIGGER IF NOT EXISTS in any version). Dropping and
-- recreating the trigger inside the migration transaction never leaves a window
-- where the table is writable to another session.
--
-- Content-free by construction (invariant 14): ids, field names, counts, states,
-- outcomes and timestamps only - never a value out of a customer message.

CREATE TABLE IF NOT EXISTS audit_log (
  workspace_id  TEXT    NOT NULL REFERENCES workspaces(id),
  -- brief 1.11 "id monotonic". IDENTITY is backed by a sequence: it never reuses
  -- an id, and BY DEFAULT (not ALWAYS) so the backfill below can keep old ids.
  id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_type    TEXT    NOT NULL DEFAULT 'system'
                        CHECK(actor_type IN ('member','system','operator')),
  actor_id      TEXT,
  event         TEXT    NOT NULL,               -- brief `action`, e.g. draft.confirmed
  object_type   TEXT,                           -- what it was done to ...
  object_id     TEXT,                           -- ... and which one
  outcome       TEXT    NOT NULL CHECK(outcome IN ('ok','denied','failed')),
  -- Defaulted in the DATABASE so a row can never be written without one. The
  -- SQLite default is lower(hex(randomblob(8))); this is the same shape (16 hex
  -- chars) without requiring the pgcrypto extension, which a managed Postgres
  -- may not let us create.
  request_id    TEXT    NOT NULL DEFAULT substr(md5(random()::text || clock_timestamp()::text), 1, 16),
  -- detail is a JSON object; the content-carrying key names are refused by the
  -- database itself. (`"body_hash":` and `"edited_fields":` are deliberately NOT
  -- matched: the patterns pin the closing quote and the colon.)
  detail        TEXT    CHECK(
                          detail IS NULL OR (
                            detail LIKE '{%}'
                            AND detail NOT LIKE '%"body":%'
                            AND detail NOT LIKE '%"text":%'
                            AND detail NOT LIKE '%"title":%'
                            AND detail NOT LIKE '%"content":%'
                            AND detail NOT LIKE '%"message":%'
                            AND detail NOT LIKE '%"summary":%'
                            AND detail NOT LIKE '%"subject":%'
                            AND detail NOT LIKE '%"permalink":%'
                            AND detail NOT LIKE '%"email":%'
                            AND detail NOT LIKE '%"name":%'
                            AND detail NOT LIKE '%"snippet":%'
                            AND detail NOT LIKE '%"quote":%'
                            AND detail NOT LIKE '%"description":%'
                            AND detail NOT LIKE '%"comment":%'
                          )
                        ),
  at            BIGINT  NOT NULL,               -- brief `occurred_at`
  -- a member actor is a real person: it must be identified.
  CHECK(actor_type <> 'member' OR actor_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS audit_log_ws_id   ON audit_log (workspace_id, id);
CREATE INDEX IF NOT EXISTS audit_log_request ON audit_log (request_id);
CREATE INDEX IF NOT EXISTS audit_log_at      ON audit_log (at);

-- ---------------------------------------------------------------------------
-- Append-only, enforced by the DATABASE (M11): "mutable by nobody" (invariant 14).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION audit_log_append_only() RETURNS trigger
LANGUAGE plpgsql AS $audit_append_only$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only: % is refused', TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$audit_append_only$;

DROP TRIGGER IF EXISTS audit_log_no_update ON audit_log;
CREATE TRIGGER audit_log_no_update
BEFORE UPDATE ON audit_log
FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();

DROP TRIGGER IF EXISTS audit_log_no_delete ON audit_log;
CREATE TRIGGER audit_log_no_delete
BEFORE DELETE ON audit_log
FOR EACH ROW EXECUTE FUNCTION audit_log_append_only();

-- ---------------------------------------------------------------------------
-- One-time backfill of any history already in the old table. Idempotent twice
-- over: NOT EXISTS skips rows already carried across, and ON CONFLICT DO NOTHING
-- covers a concurrent boot. Postgres has no `INSERT OR IGNORE`, and ON CONFLICT
-- does NOT swallow a CHECK violation the way SQLite's OR IGNORE does, so the
-- content check is repeated in the WHERE clause: a legacy row that could not
-- satisfy it is skipped rather than aborting the boot. On a fresh database this
-- copies nothing.
-- ---------------------------------------------------------------------------
INSERT INTO audit_log (workspace_id, id, actor_type, event, outcome, detail, at)
SELECT a.workspace_id, a.id, 'system', a.event, a.outcome, a.detail, a.at
  FROM audit_events a
 WHERE NOT EXISTS (SELECT 1 FROM audit_log l WHERE l.id = a.id)
   AND (
       a.detail IS NULL OR (
         a.detail LIKE '{%}'
         AND a.detail NOT LIKE '%"body":%'
         AND a.detail NOT LIKE '%"text":%'
         AND a.detail NOT LIKE '%"title":%'
         AND a.detail NOT LIKE '%"content":%'
         AND a.detail NOT LIKE '%"message":%'
         AND a.detail NOT LIKE '%"summary":%'
         AND a.detail NOT LIKE '%"subject":%'
         AND a.detail NOT LIKE '%"permalink":%'
         AND a.detail NOT LIKE '%"email":%'
         AND a.detail NOT LIKE '%"name":%'
         AND a.detail NOT LIKE '%"snippet":%'
         AND a.detail NOT LIKE '%"quote":%'
         AND a.detail NOT LIKE '%"description":%'
         AND a.detail NOT LIKE '%"comment":%'
       )
       )
ON CONFLICT DO NOTHING;

-- Ids were inserted explicitly above, which does not advance the identity
-- sequence; without this the next generated id would collide with a copied one.
-- setval(..., max+1, false) is idempotent and correct on a fresh database too.
SELECT setval(
  pg_get_serial_sequence('audit_log', 'id'),
  COALESCE((SELECT MAX(id) FROM audit_log), 0) + 1,
  false
);
